config/routes.rb
Rails.application.routes.draw do
  resources :auctions
  root :to =>'pages#home'
  
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  resources :users, :only => [:index, :new, :create, :edit, :update]  # no delete
  resources :solds
  resources :properties




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sold.rb
class Sold < ApplicationRecord
  belongs_to :property
end

app/controllers/solds_controller.rb
class SoldsController < ApplicationController
  before_action :set_sold, only: [:show, :edit, :update, :destroy]

  # GET /solds
  # GET /solds.json
  def index
    @solds = Sold.all
  end

  # GET /solds/1
  # GET /solds/1.json
  def show
  end

  # GET /solds/new
  def new
    @sold = Sold.new
  end

  # GET /solds/1/edit
  def edit
  end

  # POST /solds
  # POST /solds.json
  def create
    @sold = Sold.new(sold_params)

    respond_to do |format|
      if @sold.save
        format.html { redirect_to @sold, notice: 'Sold was successfully created.' }
        format.json { render :show, status: :created, location: @sold }
      else
        format.html { render :new }
        format.json { render json: @sold.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /solds/1
  # PATCH/PUT /solds/1.json
  def update
    respond_to do |format|
      if @sold.update(sold_params)
        format.html { redirect_to @sold, notice: 'Sold was successfully updated.' }
        format.json { render :show, status: :ok, location: @sold }
      else
        format.html { render :edit }
        format.json { render json: @sold.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /solds/1
  # DELETE /solds/1.json
  def destroy
    @sold.destroy
    respond_to do |format|
      format.html { redirect_to solds_url, notice: 'Sold was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sold
      @sold = Sold.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sold_params
      params.fetch(:sold, {})
    end
end

app/helpers/solds_helper.rb
module SoldsHelper
end

app/views/solds/_form.html.erb
<%= form_with(model: sold, local: true) do |form| %>
  <% if sold.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sold.errors.count, "error") %> prohibited this sold from being saved:</h2>

      <ul>
      <% sold.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/solds/edit.html.erb
<h1>Editing Sold</h1>

<%= render 'form', sold: @sold %>

<%= link_to 'Show', @sold %> |
<%= link_to 'Back', solds_path %>

app/views/solds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Solds</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @solds.each do |sold| %>
      <tr>
        <td><%= link_to 'Show', sold %></td>
        <td><%= link_to 'Edit', edit_sold_path(sold) %></td>
        <td><%= link_to 'Destroy', sold, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sold', new_sold_path %>

app/views/solds/new.html.erb
<h1>New Sold</h1>

<%= render 'form', sold: @sold %>

<%= link_to 'Back', solds_path %>

app/views/solds/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_sold_path(@sold) %> |
<%= link_to 'Back', solds_path %>