config/routes.rb
Rails.application.routes.draw do
  resources :auctions
  root :to =>'pages#home'
  
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  resources :users, :only => [:index, :new, :create, :edit, :update]  # no delete
  resources :solds
  resources :properties




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/auction.rb
class Auction < ApplicationRecord
  belongs_to :property
  belongs_to :user
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  before_action :set_auction, only: [:show, :edit, :update, :destroy]

  # GET /auctions
  # GET /auctions.json
  def index
    @auctions = Auction.all
    # render :json => @auctions.to_json(:include => :user,  :property)



  end

  # GET /auctions/1
  # GET /auctions/1.json
  def show
  end

  # GET /auctions/new
  def new
    @auction = Auction.new
  end

  # GET /auctions/1/edit
  def edit
  end

  # POST /auctions
  # POST /auctions.json
  def create
    @auction = Auction.new(auction_params)

    respond_to do |format|
      if @auction.save
        format.html { redirect_to @auction, notice: 'Auction was successfully created.' }
        format.json { render :show, status: :created, location: @auction }
      else
        format.html { render :new }
        format.json { render json: @auction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /auctions/1
  # PATCH/PUT /auctions/1.json
  def update
    respond_to do |format|
      if @auction.update(auction_params)
        format.html { redirect_to @auction, notice: 'Auction was successfully updated.' }
        format.json { render :show, status: :ok, location: @auction }
      else
        format.html { render :edit }
        format.json { render json: @auction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /auctions/1
  # DELETE /auctions/1.json
  def destroy
    @auction.destroy
    respond_to do |format|
      format.html { redirect_to auctions_url, notice: 'Auction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_auction
      @auction = Auction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def auction_params
      params.require(:auction).permit(:user_id,:property_id,:price)
    end
end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/views/auctions/_form.html.erb
<%= form_with(model: auction, local: true) do |form| %>
  <% if auction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(auction.errors.count, "error") %> prohibited this auction from being saved:</h2>

      <ul>
      <% auction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/auctions/edit.html.erb
<h1>Editing Auction</h1>

<%= render 'form', auction: @auction %>

<%= link_to 'Show', @auction %> |
<%= link_to 'Back', auctions_path %>

app/views/auctions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Auctions</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @auctions.each do |auction| %>
      <tr>
        <td><%= auction.property.address %>
        <td><%= auction.user.name %></td>
        <td><%= auction.price %></td>
        <td><%= link_to 'Show', auction %></td>
        <td><%= link_to 'Edit', edit_auction_path(auction) %></td>
        <td><%= link_to 'Destroy', auction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Auction', new_auction_path %>

app/views/auctions/new.html.erb
<h1>New Auction</h1>

<%= render 'form', auction: @auction %>

<%= link_to 'Back', auctions_path %>

app/views/auctions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_auction_path(@auction) %> |
<%= link_to 'Back', auctions_path %>