config/routes.rb
Rails.application.routes.draw do
  resources :auctions
  root :to =>'pages#home'
  
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  resources :users, :only => [:index, :new, :create, :edit, :update]  # no delete
  resources :solds
  resources :properties




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/property.rb
class Property < ApplicationRecord
  has_many :solds
  has_many :auctions
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  # GET /properties
  # GET /properties.json
  def index
    # @properties = Property.all('date')  ## Who put this in? What is ('date') intended to do ?
    @properties = Property.all
    respond_to do |format|
      format.html {} # do nothing - this is the default. display as normal html
      format.json {render :json => @properties}
    end
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
    property = Property.find params[:id]
    respond_to do |format|
      format.html {}
      format.json { render :json => property}
    end
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
      # respond_to do |format|
      #   if @property.update(property_params)
      #     format.html { redirect_to @property, notice: 'Property was successfully updated.' }
      #     format.json { render :show, status: :ok, location: @property }
      #   else
      #     format.html { render :edit }
      #     format.json { render json: @property.errors, status: :unprocessable_entity }
      #   end
      # end
    property = Property.find params[:id]
    # raise
    if params["property"]["photo"].nil?
      property.update property_params
    else
      cloudinary = Cloudinary::Uploader.upload( params[ "property" ][ "photo" ] )
      # link = cloudinary["url"]
      # raise
      # property.update :photo => link
      # property.update :photo => cloudinary["url"]  # JOSH FIX
      property.photo = cloudinary["url"] #John Original Code


    end
    # raise
    property.update property_params #John Original Code
    redirect_to property

  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      #params.fetch(:property, {})
      params.require(:property).permit(:address, :suburb, :landsize, :bedrooms, :bathrooms, :private_parking, :expected_price)
    end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.erb
<%= form_for @property, :html => { :multipart => true } do |form| %>





  <% if property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="fields_go_here">

    <div class="form-group">
      <%= form.label :address %>
      <%= form.text_area :address, :class => 'form-control', :required => true   %>
    </div>

    <div class="form-group">
      <%= form.label :suburb %>
      <%= form.text_field :suburb, :class => 'form-control', :required => true   %>
    </div>

    <div class="form-group">
      <%= form.label :landsize %>
      <%= form.text_field :landsize, :class => 'form-control', :required => true   %>
    </div>

    <div class="form-group">
      <%= form.label :bedrooms %>
      <%= form.text_field :bedrooms, :class => 'form-control', :required => true   %>
    </div>

    <div class="form-group">
      <%= form.label :bathrooms %>
      <%= form.text_field :bathrooms, :class => 'form-control', :required => true   %>
    </div>

    <div class="form-group">
      <%= form.label :private_parking %>
      <%= form.text_field :private_parking, :class => 'form-control', :required => true   %>
    </div>

    <div class="form-group">
      <%= form.label :expected_price %>
      <%= form.text_field :expected_price, :class => 'form-control', :required => true   %>
    </div>

    <div class="form-group">
      <%= form.label :photo %>
      <%= form.file_field :photo, :class => 'form-control'   %>
    </div>

  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

  <!-- <div class="form-group">
    <label></label>
    <%= form.submit :class => 'btn btn-info'  %>
  </div> -->

<% end %>

app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Properties</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.address %></td>
        <td><%= property.suburb %></td>
        <td><%= property.landsize %></td>
        <td><%= property.bedrooms %></td>
        <td><%= property.bathrooms %></td>
        <td><%= property.expected_price %></td>
        <td><%= link_to 'Show', property %></td>
        <td><%= link_to 'Edit', edit_property_path(property) %></td>
        <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property', new_property_path %>

app/views/properties/new.html.erb
<h1>New Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<div class="col-md-3" >
  <ul>
    <li>Address: <%= @property.address %></li>
    <li>Suburb: <%= @property.suburb %></li>
    <li>Landsize: <%= @property.landsize %></li>
    <li>Bedrooms: <%= @property.bedrooms %></li>
    <li>Bathrooms: <%= @property.bathrooms %></li>
    <li>Private Parking: <%= @property.private_parking %></li>
    <li>Expected Price: <%= @property.expected_price %></li>
    <li>Photo: <%= @property.photo %></li>
  </ul>


  <% if @property.photo.nil? %>
  <% else %>
  <div class=" mt-1em ">
    <%= image_tag(@property.photo, :class => 'img-rounded photo') unless @property.photo.nil? %>
  </div>
  <% end %>



</div>




<%= link_to 'Edit', edit_property_path(@property) %> |
<%= link_to 'Back', properties_path %>